<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="./construction.xsl"?>
<!DOCTYPE jobs [
        <!ELEMENT jobs (job)*> <!-- jobs' root element --> 
        <!ELEMENT job (startDate|endDate|address|workers|equipments|supplies|contractors)*> <!-- Child Elements of jobs -->
        <!ELEMENT startDate (#PCDATA)> <!-- Data contained by Start Date -->
        <!ELEMENT endDate (#PCDATA)>
        <!ELEMENT address (street|city|region|country)*>
        <!ELEMENT street (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT region (#PCDATA)>
        <!ELEMENT country (#PCDATA)>
        <!ELEMENT workers (worker)*>
        <!ELEMENT worker (firstName|lastName|role)*>
        <!ELEMENT firstName (#PCDATA)>
        <!ELEMENT lastName (#PCDATA)>
        <!ELEMENT role (#PCDATA)>
        <!ELEMENT equipments (equipment)*>
        <!ELEMENT equipment (type|quantity)*>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT quantity (#PCDATA)>
        <!ELEMENT supplies (supply)*>
        <!ELEMENT supply (material|qty)*>
        <!ELEMENT material (#PCDATA)>
        <!ELEMENT qty (#PCDATA)>
        <!ELEMENT contractors (name)*>
        <!ELEMENT name (#PCDATA)>
        ]>
<jobs><!-- root element -->
    <job><!-- child element of jobs -->
        <startDate>2007-08-19</startDate><!-- child element of job -->
        <endDate>2018-01-19</endDate>
        <address>//street, city...
            <street>48 Rusk Street</street> <!-- child element of address -->
            <city>La Plaine-Saint-Denis</city>
            <region>Île-de-France</region>
            <country>France</country>
        </address>
        <workers>
            <worker>
                <firstName>Tiffany</firstName>
                <lastName>Strachan</lastName>
                <role>Supervisor</role>
            </worker>
            <worker>
                <firstName>Desirae</firstName>
                <lastName>Bryett</lastName>
                <role>Surveyor</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Skid-Steer</type>
                <quantity>9</quantity>
            </equipment>
            <equipment>
                <type>Scraper</type>
                <quantity>6</quantity>
            </equipment>
            <equipment>
                <type>Dragline</type>
                <quantity>10</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Steel</material>
                <qty>6</qty>
            </supply>
            <supply>
                <material>Granite</material>
                <qty>2</qty>
            </supply>
            <supply>
                <material>Vinyl</material>
                <qty>1</qty>
            </supply>
            <supply>
                <material>Brass</material>
                <qty>1</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2006-09-02</startDate>
        <endDate>2012-04-01</endDate>
        <address>
            <street>30279 Bobwhite Court</street>
            <city>Saint-Lin-Laurentides</city>
            <region>Québec</region>
            <country>Canada</country>
        </address>
        <contractors>
            <name>Fahey-Leffler</name>
        </contractors>
        <workers>
            <worker>
                <firstName>Wain</firstName>
                <lastName>Leonards</lastName>
                <role>Construction Worker</role>
            </worker>
            <worker>
                <firstName>Traver</firstName>
                <lastName>Thiolier</lastName>
                <role>Project Manager</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Excavator</type>
                <quantity>0</quantity>
            </equipment>
            <equipment>
                <type>Excavator</type>
                <quantity>10</quantity>
            </equipment>
            <equipment>
                <type>Dragline</type>
                <quantity>0</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Glass</material>
                <qty>1</qty>
            </supply>
            <supply>
                <material>Plastic</material>
                <qty>8</qty>
            </supply>
            <supply>
                <material>Vinyl</material>
                <qty>7</qty>
            </supply>
            <supply>
                <material>Plexiglass</material>
                <qty>7</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2005-01-27</startDate>
        <endDate>2018-02-15</endDate>
        <address>
            <street>46 Ohio Street</street>
            <city>Charlotte</city>
            <region>North Carolina</region>
            <country>United States</country>
        </address>
        <contractors>
            <name>Gutmann-Rowe</name>
        </contractors>
        <workers>
            <worker>
                <firstName>Manfred</firstName>
                <lastName>Lamden</lastName>
                <role>Construction Manager</role>
            </worker>
            <worker>
                <firstName>Patty</firstName>
                <lastName>Bridell</lastName>
                <role>Construction Expeditor</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Grader</type>
                <quantity>2</quantity>
            </equipment>
            <equipment>
                <type>Backhoe</type>
                <quantity>3</quantity>
            </equipment>
            <equipment>
                <type>Dump Truck</type>
                <quantity>8</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Aluminum</material>
                <qty>5</qty>
            </supply>
            <supply>
                <material>Stone</material>
                <qty>3</qty>
            </supply>
            <supply>
                <material>Granite</material>
                <qty>2</qty>
            </supply>
            <supply>
                <material>Rubber</material>
                <qty>8</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2006-06-26</startDate>
        <endDate>2024-06-28</endDate>
        <address>
            <street>18 Karstens Hill</street>
            <city>Honolulu</city>
            <region>Hawaii</region>
            <country>United States</country>
        </address>
        <contractors>
            <name>Wisoky Inc</name>
        </contractors>
        <workers>
            <worker>
                <firstName>Shina</firstName>
                <lastName>Blowfelde</lastName>
                <role>Engineer</role>
            </worker>
            <worker>
                <firstName>Fredericka</firstName>
                <lastName>Batters</lastName>
                <role>Project Manager</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Grader</type>
                <quantity>0</quantity>
            </equipment>
            <equipment>
                <type>Scraper</type>
                <quantity>5</quantity>
            </equipment>
            <equipment>
                <type>Excavator</type>
                <quantity>0</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Rubber</material>
                <qty>0</qty>
            </supply>
            <supply>
                <material>Vinyl</material>
                <qty>7</qty>
            </supply>
            <supply>
                <material>Stone</material>
                <qty>0</qty>
            </supply>
            <supply>
                <material>Wood</material>
                <qty>6</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2007-02-22</startDate>
        <endDate>2022-09-10</endDate>
        <address>
            <street>9929 Gale Court</street>
            <city>Saint-Étienne</city>
            <region>Rhône-Alpes</region>
            <country>France</country>
        </address>
        <workers>
            <worker>
                <firstName>Lesly</firstName>
                <lastName>Moylane</lastName>
                <role>Construction Worker</role>
            </worker>
            <worker>
                <firstName>Gayleen</firstName>
                <lastName>Hubbucks</lastName>
                <role>Electrician</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Scraper</type>
                <quantity>1</quantity>
            </equipment>
            <equipment>
                <type>Compactor</type>
                <quantity>2</quantity>
            </equipment>
            <equipment>
                <type>Scraper</type>
                <quantity>9</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Aluminum</material>
                <qty>0</qty>
            </supply>
            <supply>
                <material>Granite</material>
                <qty>8</qty>
            </supply>
            <supply>
                <material>Plexiglass</material>
                <qty>2</qty>
            </supply>
            <supply>
                <material>Granite</material>
                <qty>6</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2007-09-24</startDate>
        <endDate>2025-03-15</endDate>
        <address>
            <street>4 Fairfield Terrace</street>
            <city>Pasadena</city>
            <region>California</region>
            <country>United States</country>
        </address>
        <contractors>
            <name>Koepp-O'Connell</name>
        </contractors>
        <workers>
            <worker>
                <firstName>Evan</firstName>
                <lastName>Byrom</lastName>
                <role>Engineer</role>
            </worker>
            <worker>
                <firstName>Trey</firstName>
                <lastName>Whistlecroft</lastName>
                <role>Supervisor</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Dragline</type>
                <quantity>3</quantity>
            </equipment>
            <equipment>
                <type>Scraper</type>
                <quantity>3</quantity>
            </equipment>
            <equipment>
                <type>Dump Truck</type>
                <quantity>1</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Plastic</material>
                <qty>7</qty>
            </supply>
            <supply>
                <material>Plexiglass</material>
                <qty>3</qty>
            </supply>
            <supply>
                <material>Glass</material>
                <qty>7</qty>
            </supply>
            <supply>
                <material>Plexiglass</material>
                <qty>6</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2005-09-12</startDate>
        <endDate>2011-11-18</endDate>
        <address>
            <street>11 Luster Crossing</street>
            <city>Paris 17</city>
            <region>Île-de-France</region>
            <country>France</country>
        </address>
        <workers>
            <worker>
                <firstName>Meade</firstName>
                <lastName>Gatiss</lastName>
                <role>Electrician</role>
            </worker>
            <worker>
                <firstName>Loralie</firstName>
                <lastName>Brocklebank</lastName>
                <role>Engineer</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Dump Truck</type>
                <quantity>7</quantity>
            </equipment>
            <equipment>
                <type>Scraper</type>
                <quantity>2</quantity>
            </equipment>
            <equipment>
                <type>Bulldozer</type>
                <quantity>2</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Granite</material>
                <qty>0</qty>
            </supply>
            <supply>
                <material>Glass</material>
                <qty>8</qty>
            </supply>
            <supply>
                <material>Wood</material>
                <qty>10</qty>
            </supply>
            <supply>
                <material>Granite</material>
                <qty>7</qty>
            </supply>
        </supplies>
    </job>


    <job>
        <startDate>2006-05-06</startDate>
        <endDate>2029-05-09</endDate>
        <address>
            <street>6851 Mcguire Circle</street>
            <city>Marystown</city>
            <region>Newfoundland and Labrador</region>
            <country>Canada</country>
        </address>
        <contractors>
            <name>Flatley, Fritsch and Kshlerin</name>
        </contractors>
        <workers>
            <worker>
                <firstName>Barnie</firstName>
                <lastName>Chominski</lastName>
                <role>Estimator</role>
            </worker>
            <worker>
                <firstName>Ricky</firstName>
                <lastName>Kidstone</lastName>
                <role>Architect</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Skid-Steer</type>
                <quantity>8</quantity>
            </equipment>
            <equipment>
                <type>Compactor</type>
                <quantity>2</quantity>
            </equipment>
            <equipment>
                <type>Backhoe</type>
                <quantity>6</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Wood</material>
                <qty>5</qty>
            </supply>
            <supply>
                <material>Glass</material>
                <qty>1</qty>
            </supply>
            <supply>
                <material>Aluminum</material>
                <qty>7</qty>
            </supply>
            <supply>
                <material>Glass</material>
                <qty>8</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2005-04-14</startDate>
        <endDate>2012-08-08</endDate>
        <address>
            <street>05 Knutson Junction</street>
            <city>Chicago</city>
            <region>Illinois</region>
            <country>United States</country>
        </address>
        <contractors>
            <name>Carroll, Dickinson and Kassulke</name>
        </contractors>
        <workers>
            <worker>
                <firstName>Thorny</firstName>
                <lastName>Keuntje</lastName>
                <role>Construction Expeditor</role>
            </worker>
            <worker>
                <firstName>Edi</firstName>
                <lastName>Kubicki</lastName>
                <role>Electrician</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Bulldozer</type>
                <quantity>4</quantity>
            </equipment>
            <equipment>
                <type>Bulldozer</type>
                <quantity>7</quantity>
            </equipment>
            <equipment>
                <type>Bulldozer</type>
                <quantity>1</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Aluminum</material>
                <qty>9</qty>
            </supply>
            <supply>
                <material>Glass</material>
                <qty>1</qty>
            </supply>
            <supply>
                <material>Glass</material>
                <qty>8</qty>
            </supply>
            <supply>
                <material>Granite</material>
                <qty>7</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2009-01-14</startDate>
        <endDate>2017-05-24</endDate>
        <address>
            <street>9796 Delladonna Circle</street>
            <city>Killarney</city>
            <region>Manitoba</region>
            <country>Canada</country>
        </address>
        <contractors>
            <name>Stiedemann-Feeney</name>
        </contractors>
        <workers>
            <worker>
                <firstName>Prisca</firstName>
                <lastName>Kubat</lastName>
                <role>Construction Foreman</role>
            </worker>
            <worker>
                <firstName>Ricki</firstName>
                <lastName>Critcher</lastName>
                <role>Supervisor</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Grader</type>
                <quantity>8</quantity>
            </equipment>
            <equipment>
                <type>Compactor</type>
                <quantity>8</quantity>
            </equipment>
            <equipment>
                <type>Grader</type>
                <quantity>1</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Plexiglass</material>
                <qty>1</qty>
            </supply>
            <supply>
                <material>Stone</material>
                <qty>2</qty>
            </supply>
            <supply>
                <material>Granite</material>
                <qty>10</qty>
            </supply>
            <supply>
                <material>Steel</material>
                <qty>3</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2007-05-26</startDate>
        <endDate>2028-10-27</endDate>
        <address>
            <street>70436 Grover Plaza</street>
            <city>Bochum</city>
            <region>Nordrhein-Westfalen</region>
            <country>Germany</country>
        </address>
        <workers>
            <worker>
                <firstName>Odie</firstName>
                <lastName>Mikalski</lastName>
                <role>Supervisor</role>
            </worker>
            <worker>
                <firstName>Aymer</firstName>
                <lastName>Barhims</lastName>
                <role>Construction Expeditor</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Dump Truck</type>
                <quantity>9</quantity>
            </equipment>
            <equipment>
                <type>Backhoe</type>
                <quantity>0</quantity>
            </equipment>
            <equipment>
                <type>Scraper</type>
                <quantity>8</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Stone</material>
                <qty>9</qty>
            </supply>
            <supply>
                <material>Granite</material>
                <qty>2</qty>
            </supply>
            <supply>
                <material>Wood</material>
                <qty>0</qty>
            </supply>
            <supply>
                <material>Granite</material>
                <qty>8</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2009-06-15</startDate>
        <endDate>2016-02-04</endDate>
        <address>
            <street>1 Arapahoe Center</street>
            <city>Dorchester</city>
            <region>Ontario</region>
            <country>Canada</country>
        </address>
        <workers>
            <worker>
                <firstName>Daniella</firstName>
                <lastName>Drysdell</lastName>
                <role>Project Manager</role>
            </worker>
            <worker>
                <firstName>Verne</firstName>
                <lastName>Boswood</lastName>
                <role>Supervisor</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Dragline</type>
                <quantity>7</quantity>
            </equipment>
            <equipment>
                <type>Scraper</type>
                <quantity>0</quantity>
            </equipment>
            <equipment>
                <type>Skid-Steer</type>
                <quantity>9</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Wood</material>
                <qty>3</qty>
            </supply>
            <supply>
                <material>Aluminum</material>
                <qty>9</qty>
            </supply>
            <supply>
                <material>Plexiglass</material>
                <qty>3</qty>
            </supply>
            <supply>
                <material>Rubber</material>
                <qty>3</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2007-08-15</startDate>
        <endDate>2015-05-08</endDate>
        <address>
            <street>64 Lukken Hill</street>
            <city>Paris 15</city>
            <region>Île-de-France</region>
            <country>France</country>
        </address>
         <contractors>
            <name>Bednar-Orn</name>
        </contractors>
        <workers>
            <worker>
                <firstName>Barbaraanne</firstName>
                <lastName>Youel</lastName>
                <role>Construction Worker</role>
            </worker>
            <worker>
                <firstName>Guido</firstName>
                <lastName>Bertram</lastName>
                <role>Project Manager</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Dragline</type>
                <quantity>1</quantity>
            </equipment>
            <equipment>
                <type>Skid-Steer</type>
                <quantity>6</quantity>
            </equipment>
            <equipment>
                <type>Compactor</type>
                <quantity>4</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Rubber</material>
                <qty>0</qty>
            </supply>
            <supply>
                <material>Aluminum</material>
                <qty>8</qty>
            </supply>
            <supply>
                <material>Plexiglass</material>
                <qty>8</qty>
            </supply>
            <supply>
                <material>Vinyl</material>
                <qty>9</qty>
            </supply>
        </supplies>
    </job>
    <job>
        <startDate>2005-10-21</startDate>
        <endDate>2010-11-06</endDate>
        <address>
            <street>25796 Hooker Circle</street>
            <city>Fullerton</city>
            <region>California</region>
            <country>United States</country>
        </address>
         <contractors>
            <name>Bednar, Kuhlman and Hyatt</name>
        </contractors>
        <workers>
            <worker>
                <firstName>Mureil</firstName>
                <lastName>Gerrill</lastName>
                <role>Supervisor</role>
            </worker>
            <worker>
                <firstName>Packston</firstName>
                <lastName>Bartens</lastName>
                <role>Project Manager</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Compactor</type>
                <quantity>4</quantity>
            </equipment>
            <equipment>
                <type>Dump Truck</type>
                <quantity>1</quantity>
            </equipment>
            <equipment>
                <type>Skid-Steer</type>
                <quantity>8</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Granite</material>
                <qty>6</qty>
            </supply>
            <supply>
                <material>Vinyl</material>
                <qty>3</qty>
            </supply>
            <supply>
                <material>Granite</material>
                <qty>6</qty>
            </supply>
            <supply>
                <material>Brass</material>
                <qty>1</qty>
            </supply>
        </supplies>
    </job>
     <job>
        <startDate>2008-07-25</startDate>
        <endDate>2013-09-03</endDate>
        <address>
            <street>78894 Fordem Trail</street>
            <city>Rueil-Malmaison</city>
            <region>Île-de-France</region>
            <country>France</country>
        </address>
        <workers>
            <worker>
                <firstName>Brooks</firstName>
                <lastName>Yakubov</lastName>
                <role>Engineer</role>
            </worker>
            <worker>
                <firstName>Elysha</firstName>
                <lastName>Grandisson</lastName>
                <role>Supervisor</role>
            </worker>
        </workers>
        <equipments>
            <equipment>
                <type>Dump Truck</type>
                <quantity>8</quantity>
            </equipment>
            <equipment>
                <type>Scraper</type>
                <quantity>6</quantity>
            </equipment>
            <equipment>
                <type>Dump Truck</type>
                <quantity>4</quantity>
            </equipment>
        </equipments>
        <supplies>
            <supply>
                <material>Rubber</material>
                <qty>4</qty>
            </supply>
            <supply>
                <material>Wood</material>
                <qty>5</qty>
            </supply>
            <supply>
                <material>Brass</material>
                <qty>7</qty>
            </supply>
            <supply>
                <material>Granite</material>
                <qty>0</qty>
            </supply>
        </supplies>
    </job>
</jobs>